A_TAG = 'a'
D_TAG = 'div'
DOMAIN_NAME = 'http://books.toscrape.com/'
DOMAIN_ALL_GENRES = "side_categories"
DOMAIN_URL_PREFIX = 'http://books.toscrape.com/catalogue/page-'
DOMAIN_NAME_STRING = 'http://books.toscrape.com/catalogue/'
HREF_TAG = 'href'
HTML_LIST_TAG = 'li'
HTML_BOOK_CLASS = 'col-xs-6 col-sm-4 col-md-3 col-lg-3'
NEXT_TAG = 'next'
PAGER_TAG = 'pager'
PAGE_SUFFIX = '.html'
NEW_SUFFIX = 'index.html'
FROM_START = 26
TO_END = -15
FROM_END = -10
MAX_VALUE = 100
MAX_PAGES = 20