all_genres_expected = {u'Autobiography': 'http://books.toscrape.com/catalogue/category/books/autobiography_27/index.html',
         u'Young Adult': 'http://books.toscrape.com/catalogue/category/books/young-adult_21/index.html',
         u'Humor': 'http://books.toscrape.com/catalogue/category/books/humor_30/index.html',
         u'Psychology': 'http://books.toscrape.com/catalogue/category/books/psychology_26/index.html',
         u'Food and Drink': 'http://books.toscrape.com/catalogue/category/books/food-and-drink_33/index.html',
         u'Travel': 'http://books.toscrape.com/catalogue/category/books/travel_2/index.html',
         u'Poetry': 'http://books.toscrape.com/catalogue/category/books/poetry_23/index.html',
         u'Fiction': 'http://books.toscrape.com/catalogue/category/books/fiction_10/index.html',
         u'Romance': 'http://books.toscrape.com/catalogue/category/books/romance_8/index.html',
         u'Religion': 'http://books.toscrape.com/catalogue/category/books/religion_12/index.html',
         u'Add a comment': 'http://books.toscrape.com/catalogue/category/books/add-a-comment_18/index.html',
         u'Music': 'http://books.toscrape.com/catalogue/category/books/music_14/index.html',
         u'Historical Fiction': 'http://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html',
         u'Womens Fiction': 'http://books.toscrape.com/catalogue/category/books/womens-fiction_9/index.html',
         u'Christian': 'http://books.toscrape.com/catalogue/category/books/christian_43/index.html',
         u'Business': 'http://books.toscrape.com/catalogue/category/books/business_35/index.html',
         u'Sports and Games': 'http://books.toscrape.com/catalogue/category/books/sports-and-games_17/index.html',
         u'Horror': 'http://books.toscrape.com/catalogue/category/books/horror_31/index.html',
         u'Philosophy': 'http://books.toscrape.com/catalogue/category/books/philosophy_7/index.html',
         u'Sequential Art': 'http://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html',
         u'Science Fiction': 'http://books.toscrape.com/catalogue/category/books/science-fiction_16/index.html',
         u'Cultural': 'http://books.toscrape.com/catalogue/category/books/cultural_49/index.html',
         u'Adult Fiction': 'http://books.toscrape.com/catalogue/category/books/adult-fiction_29/index.html',
         u'Erotica': 'http://books.toscrape.com/catalogue/category/books/erotica_50/index.html',
         u'New Adult': 'http://books.toscrape.com/catalogue/category/books/new-adult_20/index.html',
         u'Short Stories': 'http://books.toscrape.com/catalogue/category/books/short-stories_45/index.html',
         u'Thriller': 'http://books.toscrape.com/catalogue/category/books/thriller_37/index.html',
         u'Contemporary': 'http://books.toscrape.com/catalogue/category/books/contemporary_38/index.html',
         u'Mystery': 'http://books.toscrape.com/catalogue/category/books/mystery_3/index.html',
         u'Default': 'http://books.toscrape.com/catalogue/category/books/default_15/index.html',
         u'Science': 'http://books.toscrape.com/catalogue/category/books/science_22/index.html',
         u'Christian Fiction': 'http://books.toscrape.com/catalogue/category/books/christian-fiction_34/index.html',
         u'Academic': 'http://books.toscrape.com/catalogue/category/books/academic_40/index.html',
         u'Historical': 'http://books.toscrape.com/catalogue/category/books/historical_42/index.html',
         u'Politics': 'http://books.toscrape.com/catalogue/category/books/politics_48/index.html',
         u'Classics': 'http://books.toscrape.com/catalogue/category/books/classics_6/index.html',
         u'History': 'http://books.toscrape.com/catalogue/category/books/history_32/index.html',
         u'Parenting': 'http://books.toscrape.com/catalogue/category/books/parenting_28/index.html',
         u'Art': 'http://books.toscrape.com/catalogue/category/books/art_25/index.html',
         u'Childrens': 'http://books.toscrape.com/catalogue/category/books/childrens_11/index.html',
         u'Spirituality': 'http://books.toscrape.com/catalogue/category/books/spirituality_39/index.html',
         u'Novels': 'http://books.toscrape.com/catalogue/category/books/novels_46/index.html',
         u'Paranormal': 'http://books.toscrape.com/catalogue/category/books/paranormal_24/index.html',
         u'Fantasy': 'http://books.toscrape.com/catalogue/category/books/fantasy_19/index.html',
         u'Self Help': 'http://books.toscrape.com/catalogue/category/books/self-help_41/index.html',
         u'Suspense': 'http://books.toscrape.com/catalogue/category/books/suspense_44/index.html',
         u'Nonfiction': 'http://books.toscrape.com/catalogue/category/books/nonfiction_13/index.html',
         u'Crime': 'http://books.toscrape.com/catalogue/category/books/crime_51/index.html',
         u'Health': 'http://books.toscrape.com/catalogue/category/books/health_47/index.html',
         u'Biography': 'http://books.toscrape.com/catalogue/category/books/biography_36/index.html'}

expected_pass_by_genre_res = {0: 'http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html', 1: 'http://books.toscrape.com/catalogue/full-moon-over-noahs-ark-an-odyssey-to-mount-ararat-and-beyond_811/index.html', 2: 'http://books.toscrape.com/catalogue/see-america-a-celebration-of-our-national-parks-treasured-sites_732/index.html', 3: 'http://books.toscrape.com/catalogue/vagabonding-an-uncommon-guide-to-the-art-of-long-term-world-travel_552/index.html', 4: 'http://books.toscrape.com/catalogue/under-the-tuscan-sun_504/index.html', 5: 'http://books.toscrape.com/catalogue/a-summer-in-europe_458/index.html', 6: 'http://books.toscrape.com/catalogue/the-great-railway-bazaar_446/index.html', 7: 'http://books.toscrape.com/catalogue/a-year-in-provence-provence-1_421/index.html', 8: 'http://books.toscrape.com/catalogue/the-road-to-little-dribbling-adventures-of-an-american-in-britain-notes-from-a-small-island-2_277/index.html', 9: 'http://books.toscrape.com/catalogue/neither-here-nor-there-travels-in-europe_198/index.html', 10: 'http://books.toscrape.com/catalogue/1000-places-to-see-before-you-die_1/index.html'}

expected_pass_by_genre_with_limit_res = {0: 'http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html', 1: 'http://books.toscrape.com/catalogue/full-moon-over-noahs-ark-an-odyssey-to-mount-ararat-and-beyond_811/index.html', 2: 'http://books.toscrape.com/catalogue/see-america-a-celebration-of-our-national-parks-treasured-sites_732/index.html', 3: 'http://books.toscrape.com/catalogue/vagabonding-an-uncommon-guide-to-the-art-of-long-term-world-travel_552/index.html', 4: 'http://books.toscrape.com/catalogue/under-the-tuscan-sun_504/index.html'}
